### ISSUE TITLE
ID'er unikke 

### ISSUE THREAD

**Issue by klementj** [mich4863/PersonalMovie_DB#1]
https://github.com/mich4863/PersonalMovie_DB/blob/0de4350f9edb95cbc44d03fac32baa9c34294391/src/scss/styles.scss#L28

Du har et ID som du bruger flere gange.
* Ét element må kun have et ID
* Én side må kun have ét element med det ID

[css-tricks.com/the-difference-between-id-and-class/](https://css-tricks.com/the-difference-between-id-and-class/)

**Comment by mich4863** [comment]
Ordnet.
Har fjernet id'et.
